### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 2, got 1)

### ISSUE THREAD

**Issue by alexpet** [ajmyers/tm1cm#8]
When running the following command in Interactive mode:
migrate mytestapplication.staging mytestapplication.test

I receive the following error:
\Error occurred:
 Traceback (most recent call last):
  File "E:\python\Lib\site-packages\tm1cm\interactive.py", line 165, in do_migrate
    self.migration = Migration(app_from, app_to)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\site-packages\tm1cm\migration.py", line 48, in __init__
    self._compute_operations()
  File "E:\python\Lib\site-packages\tm1cm\migration.py", line 94, in _compute_operations
    folder, sub_folder, *object_a = diff_added.a_path.split(os.sep)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected at least 2, got 1)

How can I resolve this error?

**Comment by ajmyers** [comment]
Hey Alex, I took a stab at replicating the issue on my side with my test environments and I didn't have any luck. As a first step for troubleshooting, can you please do the following:

1. Optional: Find and clear the .log file. It's likely in your project directory called mytestapplication.log. It may also be in the working directory wherever you are running the tm1cm command from
2. Launch tm1cm with the debug flag:
`tm1cm --debug`
3. Repeat the steps above that caused the issue
4. Post the contents of the .log file

Hopefully I'll be able to determine the issue that way

**Comment by ZHENGHECHU** [comment]
Hello @alexpet 

I had the totally issue with you and i tried to slightly modified the 2 lines (highlight in bold)  in def  _compute_operations in Class migration and then it worked for me.

Need kindly recheck of @ajmyers , thank you for your help. 

`    def _compute_operations(self):
        head_commit = self.repo.head.commit
        self._operations = []
        for diff_added in head_commit.diff(None):
            change_type = diff_added.change_type[:1]
            
            **folder, sub_folder, *object_a = diff_added.a_path.split(os.sep)[0].split("/")**
            object_a = os.sep.join(object_a)

            try:
                object_a_name, object_a_ext = object_a.rsplit('.', 1)
            except Exception:
                object_a_name = object_a

            **_, _, *object_b = diff_added.b_path.split(os.sep)[0].split("/")**
            object_b = os.sep.join(object_b)
            
            try:
                object_b_name, object_b_ext = object_b.rsplit('.', 1)
            except Exception:
                object_b_name = object_b
            if folder == 'data':
                op = self._get_operation_list(change_type, object_b_ext, object_b_name, object_a_name)
            else:
                op = self._get_operation_list(change_type, 'file', diff_added.b_path, diff_added.a_path)

            self._operations.extend(op)`

**Comment by ajmyers** [comment]
Thanks @alexpet and @ZHENGHECHU, that's helpful in narrowing it down. It appears the issue might be windows related, let me dust off my old PC and see if i can replicate and push a fix

**Comment by ZHENGHECHU** [comment]
Hello @ajmyers ,
thank you for your quickly reply. 
One more little issue i found when i set text_output_format: JSON in the  tm1cm.yaml file (YAML worked perfectly in  my side), the error message showed that  "module 'json' has no attribute 'safe_load'", could you please also take a look? 
```
# JSON or YAML -- recommended to use YAML as its human-readable
text_output_format: JSON
```
error message: 
```

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AppData\Local\Programs\Python\Python311\Scripts\tm1cm.exe\__main__.py", line 7, in <module>
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tm1cm\__main__.py", line 45, in main
    function(local_config, local_path, remote_session)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tm1cm\__main__.py", line 58, in put
    app_from = LocalApplication(config, path).refresh(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\site-packages\tm1cm\application.py", line 68, in refresh
    self._populate(overlay)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tm1cm\application.py", line 694, in _populate
    result.append(self.load(fp))
                  ^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\tm1cm\application.py", line 366, in load
    data = json.safe_load(fp, indent=4, sort_keys=True, ensure_ascii=False)
           ^^^^^^^^^^^^^^
AttributeError: module 'json' has no attribute 'safe_load'
```

**Comment by ajmyers** [comment]
Hey @alexpet and @ZHENGHECHU, I've pushed a fix for the above issues, and published a new build to pypi
```
pip install --upgrade tm1cm
```
Should get you the latest
